name = "article-processor"
compatibility_date = "2024-03-04"

[build]
command = "npm run build:client"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ecoutable"

[[d1_databases]]
binding = "DB"
database_name = "ecoutable"
database_id = "785b7464-f198-428b-8f50-7bff5b3c1ccf"
migrations_dir = "migrations"

[vars]
