name = "article-processor"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build:client"

[[r2_buckets]]
binding = "ECOUTABLE_BUCKET"
bucket_name = "ecoutable-bucket"

[[kv_namespaces]]
binding = "ECOUTABLE_KV"
id = "ec5a0d0b-c0c7-4f6f-a2c5-f9f8c4b6b9b3"

[vars]
DATABASE_URL = ""
